; ============================================================
; Pattern Miner Mini Project - Knowledge Base
; ============================================================

(Inheritance Alice Human)
(Inheritance Bob Human)
(Inheritance Charlie Human)
(Inheritance David Human)

(Inheritance Dog Animal)

(Evaluation (Likes Alice Soda))
(Evaluation (Likes Bob Soda))
(Evaluation (Likes Charlie Soda))

(Evaluation (Likes Alice Pizza))
(Evaluation (Likes Bob Pizza))
(Evaluation (Likes Charlie Pizza))

(Evaluation (Likes David Salad))
